config/routes.rb
Rails.application.routes.draw do
  # Nest employees resources within firms
  resources :firms do
    resources :employees, except: :index
  end
  get '/firms/:firm_id/employees/:id/edit_preferences', to: 'employees#edit_preferences', as: 'edit_preferences'
  get '/firms/:firm_id/employees/:id/request_off', to: 'employees#request_off', as: 'request_off'
  post '/firms/:firm_id/employees/:id/handle_request_off', to: 'employees#handle_request_off', as: 'handle_request_off'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/firm.rb
class Firm < ApplicationRecord
  has_many :employees, dependent: :destroy
  has_many :days, dependent: :destroy

  # so awesome, a most helpful helper method
  def auto_schedule_week(begin_date)
    week = []

    # For each day in the week
    for i in 0..6

      the_date = begin_date + i
      the_day = Day.find_by(date: the_date, firm: self)
      week.push(the_day)
    end

  end

end

app/controllers/firms_controller.rb
class FirmsController < ApplicationController
  before_action :set_firm, only: [:show, :edit, :update, :destroy]

  # GET /firms
  # GET /firms.json
  def index
    @firms = Firm.all
  end

  # GET /firms/1
  # GET /firms/1.json
  def show
  end

  # GET /firms/new
  def new
    @firm = Firm.new
  end

  # GET /firms/1/edit
  def edit
    # would add error-handling here
  end

  # POST /firms
  # POST /firms.json
  def create
    @firm = Firm.new(firm_params)

    respond_to do |format|
      if @firm.save
        format.html { redirect_to @firm, notice: 'Firm was successfully created.' }
        format.json { render :show, status: :created, location: @firm }
      else
        format.html { render :new }
        format.json { render json: @firm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /firms/1
  # PATCH/PUT /firms/1.json
  def update
    # i'd remove the json respond_to block-- this is scaffolding bloat
    respond_to do |format|
      if @firm.update(firm_params)
        format.html { redirect_to @firm, notice: 'Firm was successfully updated.' }
        format.json { render :show, status: :ok, location: @firm }
      else
        format.html { render :edit }
        format.json { render json: @firm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /firms/1
  # DELETE /firms/1.json
  def destroy
    @firm.destroy
    respond_to do |format|
      format.html { redirect_to firms_url, notice: 'Firm was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_firm
      @firm = Firm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def firm_params
      params.require(:firm).permit(:name, :phone_number, :address, :city, :state, :zip_code,
        :mon_open_time, :mon_close_time, :tue_open_time, :tue_close_time,
        :wed_open_time, :wed_close_time, :thu_open_time, :thu_close_time,
        :fri_open_time, :fri_close_time,
      )
    end
end

app/helpers/firms_helper.rb
module FirmsHelper
end

app/views/firms/_availability_calendar.html.erb
<span class="label can-work">Can Work</span>
<span class="label cannot-work-weak">Prefers Off</span>
<span class="label cannot-work-strong">Strongly Prefers Off</span>
<span class="label requested-off">Specifically Requested Off</span>
<br>
<br>
<br>


<%= month_calendar do |date| %>
    <strong><%= date.strftime("%e") %></strong>
    <% @firm.employees.each do |employee| %>

      <div>
        <span class="label <%= employee.get_pref_class(date) %>"><%= employee.first_name %> <%= employee.last_name %></span>
      </div>
    <%	end %>

<% end %>

app/views/firms/_contact_info.html.erb
<table>
  <tr>
    <td>Phone Number:</td><td><%=	@firm.phone_number %></td>
  </tr>
  <tr>
    <td>Address:</td><td><%=	@firm.address %></td>
  </tr>
  <tr>
    <td></td><td><%=@firm.city %>, <%=	@firm.state %> <%=	@firm.zip_code %></td>
  </tr>
</table>

app/views/firms/_form.html.erb
<%= form_for(firm) do |f| %>
  <% if firm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(firm.errors.count, "error") %> prohibited this firm from being saved:</h2>

      <ul>
      <% firm.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="fields">
    <table>
      <tr>
        <td><%= f.label :name %></td>
        <td><%= f.text_field :name %></td>
      </tr>

      <tr>
        <td><%= f.label :phone_number %></td>
        <td><%= f.text_field :phone_number %></td>
      </tr>

      <tr>
        <td><%= f.label :address %></td>
        <td> <%= f.text_field :address %></td>
      </tr>

      <tr>
        <td><%= f.label :city %></td>
        <td><%= f.text_field :city %></td>
      </tr>

      <tr>
        <td><%= f.label :state %></td>
        <td><%= f.text_field :state %></td>
      </tr>

      <tr>
        <td><%= f.label :zip_code %></td>
        <td><%= f.text_field :zip_code %></td>
      </tr>


    </table>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/firms/_schedule_calendar.html.erb
<span class="label can-work">Can Work</span>
<span class="label cannot-work-weak">Prefers Off</span>
<span class="label cannot-work-strong">Strongly Prefers Off</span>
<span class="label requested-off">Specifically Requested Off</span>
<br>
<br>
<br>



<%= month_calendar do |date| %>
    <!-- excellent leveraging of .strftime in general through out this app -->
    <strong><%= date.strftime("%e") %></strong>
    <% @firm.employees.each do |employee| %>

        <div>
          <% if employee.first_name == 'Tim' %>
              <span class="employee label label-default">
                <strong><%= employee.first_name %> <%= employee.last_name %></strong>
              </span>
          <%	else  %>
              <span class="label <%= employee.get_pref_class(date) %>">
                <%= employee.first_name %> <%= employee.last_name %>
              </span>
          <%	end %>
        </div>
    <%	end %>

<% end %>

<!-- i would remove this -->
<script type="text/javascript" charset="utf-8">

</script>

app/views/firms/edit.html.erb
<h1>Editing Firm</h1>

<%= render 'form', firm: @firm %>

<%= link_to 'Show', @firm %> |
<%= link_to 'Back', firms_path %>

app/views/firms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Firms</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <!-- perfectly appropriate, good use of a table -->
  <tbody>
    <% @firms.each do |firm| %>
      <tr>
        <td><%= firm.name %></td>
        <td><%= link_to 'Show', firm %></td>
        <td><%= link_to 'Edit', edit_firm_path(firm) %></td>
        <td><%= link_to 'Destroy', firm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Firm', new_firm_path %>

app/views/firms/new.html.erb
<h1>New Firm</h1>

<%= render 'form', firm: @firm %>

<%= link_to 'Back', firms_path %>

app/views/firms/show.html.erb
<p id="notice"><%= notice %></p>
<h2><%=	@firm.name %></h2>
<%= link_to 'Edit', edit_firm_path(@firm) %> |
<%= link_to 'Back', firms_path %>
<hr>
<h3>Employees</h3>
<%= link_to 'New', new_firm_employee_path(@firm) %>
<%	if @firm.employees.size > 0 %>
    <br><br>
    <table>
      <tr>
        <th>Name</th><th>Phone Number</th><th>Email Address</th>
      </tr>
      <%	 @firm.employees.each do |employee| %>
          <tr>
            <td><%=	employee.first_name %> <%=	employee.last_name %></td>
            <td><%=	employee.phone_number %></td>
            <td><%=	employee.email_address %></td>
            <td><%= link_to 'Show Details', [@firm, employee] %></td>

          </tr>
      <% end %>
    </table>
<% else %>
<!-- yay 'error' handling  -->
  <p>No employees have been created.</p>
<%	end %>
<hr>
<h3>Availability Calendar</h3>
<%=	render partial: "availability_calendar" %>