config/routes.rb
Rails.application.routes.draw do
  # Nest employees resources within firms
  resources :firms do
    resources :employees, except: :index
  end
  get '/firms/:firm_id/employees/:id/edit_preferences', to: 'employees#edit_preferences', as: 'edit_preferences'
  get '/firms/:firm_id/employees/:id/request_off', to: 'employees#request_off', as: 'request_off'
  post '/firms/:firm_id/employees/:id/handle_request_off', to: 'employees#handle_request_off', as: 'handle_request_off'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :firm
  # should add has_many :shifts here-- it seems like there are portions of your code that might be simplified by leveraging employee_instance.shifts. see comments below

  def get_pref_text(date)
    # i might make mapping a class method for employee, or possibly an instance method, since it's used in different portions of your program
    mapping = {0.0 => "Prefers Off", 0.5 => "Strongly Prefers Off", 1.0 => "Can work"}

    # Check if the day was requested off specifically

    # this might be one area that could be simplified by something like self.shifts.find_by(date: date)
    the_day = Day.find_by(date: date, firm: self.firm)
    if the_day
      the_shift = Shift.find_by(employee: self, day: the_day)
      if the_shift
        if the_shift.requrested_off == true
          return "Requested Off"
        end
      end
    end

    # If not requested off, go to the specific preferences
    case date.strftime("%a")
      when "Mon"
        val = self.mon_pref
      when "Tue"
        val = self.tue_pref
      when "Wed"
        val = self.wed_pref
      when "Thu"
        val = self.thu_pref
      when "Fri"
        val = self.fri_pref
      when "Sat"
        val = self.sat_pref
      when "Sun"
        val = self.sun_pref
    end

    return mapping[val]
  end

  def get_pref_val(date)

    case date.strftime("%a")
      when "Mon"
        val = self.mon_pref
      when "Tue"
        val = self.tue_pref
      when "Wed"
        val = self.wed_pref
      when "Thu"
        val = self.thu_pref
      when "Fri"
        val = self.fri_pref
      when "Sat"
        val = self.sat_pref
      when "Sun"
        val = self.sun_pref
    end

    return val
  end

  def get_pref_class(date)
    mapping = {0.0 => "cannot-work-strong", 0.5 => "cannot-work-weak", 1.0 => "can-work"}
    # might be able to roll this into get pref_text_class (or have a swiss-army style get_pref funciton whose second arg tells it what type of thing to return) or leverage that in your view somehow

    # Check if the day was requested off specifically
    the_day = Day.find_by(date: date, firm: self.firm)
    if the_day
      the_shift = Shift.find_by(employee: self, day: the_day)
      if the_shift
        if the_shift.requested_off == true
          return "requested-off"
        end
      end
    end

    # If not requested off, go to the specific preferences
    case date.strftime("%a")
      when "Mon"
        val = self.mon_pref
      when "Tue"
        val = self.tue_pref
      when "Wed"
        val = self.wed_pref
      when "Thu"
        val = self.thu_pref
      when "Fri"
        val = self.fri_pref
      when "Sat"
        val = self.sat_pref
      when "Sun"
        val = self.sun_pref
    end

    return mapping[val]
  end

  def request_off(date)
    # i think you could shorten these by one line by taking out the variable def and instead just saying if `Day.find_by(date: date, firm: self.firm)` but not sure it's really worth it ^.^ just a thought
    the_day = Day.find_by(date: date, firm: self.firm)
    if not the_day
      the_day = Day.create!(date: date, firm: self.firm)
    end

    requesting_off = Shift.find_by(employee: self, day: the_day)
    if not requesting_off
      requesting_off = Shift.create(employee: self, day: the_day)
    end

    requesting_off.update!(requested_off: true)
  end

  def cancel_request_off(date)
    the_day = Day.find_by(date: date, firm: self.firm)

    if the_day
      requesting_off = Shift.find_by(employee: self, day: the_day)
      # if it doesn't exist yet, it creates it! cool.
      if not requesting_off
        requesting_off = Shift.create(employee: self, day: the_day)
      end

      requesting_off.update!(requested_off: false)
      # possibly add error handling here
    end


  end

  # super helpful helper method
  def schedule(date)
    the_day = Day.find_by(date: date, firm: self.firm)
    if not the_day
      the_day = Day.create!(date: date, firm: self.firm)
    end

    scheduled = Shift.find_by(employee: self, day: the_day)
    if not requesting_off
      scheduled = Shift.create(employee: self, day: the_day)
    end

    scheduled.update!(is_scheduled: true)
  end


  # i suspect this might be duplicating functionality built into rails in the sense that an employee's shifts belong to it through the join. see my comment above. ultimately, you could return something like self.shifts.find_by(date).is_scheduled, and just have that be the entire method
  def get_is_scheduled(date)
    # If the day and the shift exist
    the_day = Day.find_by(date: date, firm: self.firm)
    if the_day
      the_shift = Shift.find_by(employee: self, day: the_day)
      if the_shift
        # If the employee is scheduled for the shift
        if the_shift.is_scheduled == true
          return true
        end
      end
    end

    # nice
    # If any of the above conditions return false
    return false
  end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  # you're running the exact same code in each of the actions actions specified above


  # GET /employees/1
  # GET /employees/1.json
  def show
    @firm = Firm.find(params[:firm_id])

  end

  # GET /employees/new
  def new
    @firm = Firm.find(params[:firm_id])
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
    @firm = Firm.find(params[:firm_id])
  end

  def edit_preferences
    @firm = Firm.find(params[:firm_id])
    @employee = Employee.find(params[:id])
  end

  # these features might go into a shifts controller
  def request_off
    @firm = Firm.find(params[:firm_id])
    @employee = Employee.find(params[:id])
  end

  def handle_request_off
    @firm = Firm.find(params[:firm_id])
    @employee = Employee.find(params[:id])
    the_day = params[:request_off_date]

    @employee.request_off(the_day)
    respond_to do |format|
      if @employee.save
        format.html { redirect_to @firm, notice: 'Day off was requested.' }
      else
        format.html { render :new }
      end
    end

  end


  # POST /employees
  # POST /employees.json
  def create
    @firm = Firm.find(params[:firm_id])
    @employee = @firm.employees.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @firm, notice: 'Employee was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
  @firm = Firm.find(params[:firm_id])
  @employee = Employee.find(params[:id])

# scaffolding bloat
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @firm, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    # you're not serving JSON so i would remove this. scaffolding generates a lot of extraneous stuff for most apps like controller tests
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :email_address, :phone_number,
          :hourly_pay_rate, :overtime_exempt, :overtime_multiplier, :lunch_duration, :max_hours_hard_limit,
          :hours_overtime_threshold, :mon_pref, :tue_pref, :wed_pref, :thu_pref, :fri_pref, :sat_pref, :sun_pref,
           :request_off_date
      )
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_employee_details.html.erb
<table>
  <tr>
    <td>Name:</td><td><%= @employee.first_name %> <%= @employee.last_name %></td>
  </tr>
  <tr>
    <td>Phone Number:</td><td><%= @employee.phone_number %></td>
  </tr>
  <tr>
    <td>Email Address:</td><td><%= @employee.email_address %></td>
  </tr>
  <tr>
    <td>Hourly Pay Rate:</td><td>$<%= @employee.hourly_pay_rate %></td>
  </tr>
  <tr>
    <td>Overtime Exempt:</td>
    <td>
      <% if @employee.overtime_exempt %>
          Yes
      <% else %>
          No
      <% end %>
    </td>
  </tr>
  <tr>
    <td>Overtime Pay Multiplier:</td><td><%= @employee.overtime_multiplier %></td>
  </tr>
  <tr>
    <td>Lunch Duration:</td><td><%= @employee.lunch_duration %> hours</td>
  </tr>
  <tr>
    <td>Max working hours (hard limit):</td>
    <td>
      <% if @employee.max_hours_hard_limit %>
        <%= @employee.max_hours_hard_limit %>
      <% else %>
        No limit
      <% end %>
    </td>
  </tr>
  <tr>
    <td>Overtime Threshold (Hours):</td><td><%= @employee.hours_overtime_threshold %></td>
  </tr>
</table>

app/views/employees/_form.html.erb
<%= form_for([@firm, @employee]) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="fields">
    <table>
      <tr>
        <td><%= f.label :first_name %></td>
        <td><%= f.text_field :first_name %></td>
      </tr>

      <tr>
        <td><%= f.label :last_name %></td>
        <td><%= f.text_field :last_name %></td>
      </tr>

      <tr>
        <td><%= f.label :email_address %></td>
        <td> <%= f.text_field :email_address %></td>
      </tr>

      <tr>
        <td><%= f.label :phone_number %></td>
        <td><%= f.text_field :phone_number %></td>
      </tr>

      <hr>

      <tr>
        <td><%= f.label :hourly_pay_rate %></td>
        <td><%= f.text_field :hourly_pay_rate %></td>
      </tr>

      <tr>
        <td><%= f.label :overtime_exempt %></td>
        <td><%= f.check_box :overtime_exempt %></td>
      </tr>

      <tr>
        <td><%= f.label :overtime_multiplier %></td>
        <td><%= f.text_field :overtime_multiplier %></td>
      </tr>
      <tr>
        <td><%= f.label :lunch_duration %></td>
        <td><%= f.text_field :lunch_duration %></td>
      </tr>
      <tr>
        <td><%= f.label :max_hours_hard_limit %></td>
        <td><%= f.text_field :max_hours_hard_limit %></td>
      </tr>
      <tr>
        <td><%= f.label :hours_overtime_threshold %></td>
        <td><%= f.text_field :hours_overtime_threshold %></td>
      </tr>
    </table>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/_preferences.html.erb
<!-- you could also make mapping a part of the Employee model -->
<% mapping = {0.0 => "Strongly Preferred Off", 0.5 => "Preferred Off", 1.0 => "Can work"} %>

<table>
  <tr>
    <td>Monday:</td>
    <td>
      <% if @employee.mon_pref %>
          <%= mapping[@employee.mon_pref] %>
      <% else %>
          Unknown
      <% end %>
    </td>
  </tr>
  <tr>
    <td>Tuesday:</td>
    <td>
      <% if @employee.tue_pref %>
          <%= mapping[@employee.tue_pref] %>
      <% else %>
          Unknown
      <% end %>
    </td>
  </tr>
  <tr>
    <td>Wednesday:</td>
    <td>
      <% if @employee.wed_pref %>
          <%= mapping[@employee.wed_pref] %>
      <% else %>
          Unknown
      <% end %>
    </td>
  </tr>
  <tr>
    <td>Thursday:</td>
    <td>
      <% if @employee.thu_pref %>
          <%= mapping[@employee.thu_pref] %>
      <% else %>
          Unknown
      <% end %>
    </td>
  </tr>
  <tr>
    <td>Friday:</td>
    <td>
      <% if @employee.fri_pref %>
          <%= mapping[@employee.fri_pref] %>
      <% else %>
          Unknown
      <% end %>
    </td>
  </tr>
  <tr>
    <td>Saturday:</td>
    <td>
      <% if @employee.sat_pref %>
          <%= mapping[@employee.sat_pref] %>
      <% else %>
          Unknown
      <% end %>
    </td>
  </tr>
  <tr>
    <td>Sunday:</td>
    <td>
      <% if @employee.sun_pref %>
          <%= mapping[@employee.sun_pref] %>
      <% else %>
          Unknown
      <% end %>
    </td>
  </tr>


</table>

app/views/employees/_preferences_form.html.erb
<%= form_for([@firm, @employee]) do |f| %>
    <% if @employee.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

          <ul>
            <% @employee.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="fields">
      <table class="time-pref">
        <tr>
          <th></th>
          <th>Can Work</th>
          <th>Prefer Off</th>
          <th>Strongly Prefer Off</th>
        </tr>
        <tr>
          <!-- you could build these forms using a do-loop leveraging that mapping hash and a hash with the weekdays -->
          <td><%= f.label :Monday %></td>
          <td><%= f.radio_button :mon_pref, 1.0 %></td>
          <td><%= f.radio_button :mon_pref, 0.5 %></td>
          <td><%= f.radio_button :mon_pref, 0.0 %></td>
        </tr>
        <tr>
          <td><%= f.label :Tuesday %></td>
          <td><%= f.radio_button :tue_pref, 1.0 %></td>
          <td><%= f.radio_button :tue_pref, 0.5 %></td>
          <td><%= f.radio_button :tue_pref, 0.0 %></td>
        </tr>
        <tr>
          <td><%= f.label :Wednesday %></td>
          <td><%= f.radio_button :wed_pref, 1.0 %></td>
          <td><%= f.radio_button :wed_pref, 0.5 %></td>
          <td><%= f.radio_button :wed_pref, 0.0 %></td>
        </tr>
        <tr>
          <td><%= f.label :Thursday %></td>
          <td><%= f.radio_button :thu_pref, 1.0 %></td>
          <td><%= f.radio_button :thu_pref, 0.5 %></td>
          <td><%= f.radio_button :thu_pref, 0.0 %></td>
        </tr>
        <tr>
          <td><%= f.label :Friday %></td>
          <td><%= f.radio_button :fri_pref, 1.0 %></td>
          <td><%= f.radio_button :fri_pref, 0.5 %></td>
          <td><%= f.radio_button :fri_pref, 0.0 %></td>
        </tr>
        <tr>
          <td><%= f.label :Saturday %></td>
          <td><%= f.radio_button :sat_pref, 1.0 %></td>
          <td><%= f.radio_button :sat_pref, 0.5 %></td>
          <td><%= f.radio_button :sat_pref, 0.0 %></td>
        </tr>
        <tr>
          <td><%= f.label :Sunday %></td>
          <td><%= f.radio_button :sun_pref, 1.0 %></td>
          <td><%= f.radio_button :sun_pref, 0.5 %></td>
          <td><%= f.radio_button :sun_pref, 0.0 %></td>
        </tr>
      </table>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/employees/_request_off_form.html.erb
<%= form_tag({controller: 'employees', action: 'handle_request_off'}, method: 'post') do |f| %>


    <div class="fields">
      <table class="time-pref">
        <tr>
          <!-- I like that an employee can only request one day off at any given time: smart restrictive UX -->
          <td><%= date_field_tag(:request_off_date) %></td>
        </tr>

      </table>
    </div>

    <div class="actions">
      <%= submit_tag "Request Day Off" %>
    </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show Details', [@firm, @employee] %> |
<%= link_to 'Back', firm_path(@firm) %>

app/views/employees/edit_preferences.html.erb
<h2><%=	@employee.first_name %> <%=	@employee.last_name %></h2>

<!-- great, super-railsy use of partials here -->
<h3>Editing Work Preferences</h3>
<%= render 'preferences_form', employee: @employee %>

<%= link_to 'Show Details', [@firm, @employee] %> |
<%= link_to 'Back', firm_path(@firm) %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

app/views/employees/request_off.html.erb
<h3>Request A Specific Day Off</h3>
<%= render partial: 'request_off_form', employee: @employee %>

<%= link_to 'Show Details', [@firm, @employee] %> |
<%= link_to 'Back', firm_path(@firm) %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @employee.first_name %> <%= @employee.last_name %></h2>

<%= link_to 'Edit Details', edit_firm_employee_path([@firm, @employee]) %> |
<%= link_to 'Back', @firm %>

<br><br><br>
<h3>Details</h3>
<%=	render partial: "employee_details" %>

<h3>Preferences</h3>
<%= link_to 'Edit Preferences', edit_preferences_path([@firm, @employee]) %>
<%= render partial: "preferences" %>

<h3>Requested Days Off</h3>
<%= link_to 'Request A Day Off', request_off_path([@firm, @employee]) %>
<%= render partial: "requested_off" %>